### ISSUE TITLE
"not a tty" when signing

### ISSUE THREAD

**Issue by gymnae** [wernight/docker-duplicity#1]
Hi,
I'm trying to get an image up an running which is close to this one, but can't get gpg to sign, did you or any user of this image encounter the same problem? Encryption seems to work, but when signing gpg just fails

http://stackoverflow.com/questions/36356924/not-a-tty-error-in-alpine-based-duplicity-image

**Comment by wernight** [comment]
Sorry didn't do any magic here. Just mount it may be

**Comment by wernight** [comment]
May be also try with `-it` docker flag.

**Comment by gymnae** [comment]
Yeah, some updates to alpine and duplicty have fixed this :) thank you
