### ISSUE TITLE
wrong username being used on rsync server

### ISSUE THREAD

**Issue by redbull-assassin** [wernight/docker-duplicity#11]
Per the documentation, I am attempting to backup a directory on the machine host to be transfered via rsync with the "net-backup" user account, unfortunately the wrong username "root" is being passed for authentication to the rsync server. 

```
core@coreos ~ $ docker run --rm -it \
>   --user root -e PASSPHRASE=P4ssw0rd \
>   -v $PWD/.cache:/home/duplicity/.cache/duplicity \
>   -v $PWD/.gnupg:/home/duplicity/.gnupg \
>   -v /backups/scripts/net-backup.key:/id_rsa:ro \
>   -v ~/.ssh/known_hosts:/etc/ssh/ssh_known_hosts:ro \
>   -v /data:/bak:ro \
>   wernight/duplicity \
>   duplicity --full-if-older-than=6M --allow-source-mismatch \
>   --rsync-options='-e "ssh -i /id_rsa"' \
>   /bak rsync://net-backup@192.168.100.10::NetBackup/cerb 
gpg: WARNING: unsafe permissions on homedir '/home/duplicity/.gnupg'
root@192.168.100.10's password: 
```

Any assistance would be appreciated

**Comment by wernight** [comment]
id_rsa may require to limit chown in order to work, and I'm not sure if you don't also need id_rsa.pub. I'd run as your user (--user $UID). Outside of that, the password it like if you did `ssh net-backup@192.168.100.10`.

**Comment by redbull-assassin** [comment]
This is definitely an rsync issue, I have reverted to sftp and it works great.

Thank you
