### ISSUE TITLE
PyDrive

### ISSUE THREAD

**Issue by ghost** [wernight/docker-duplicity#2]
I'm getting the following error when using pydrive

`BackendException: PyDrive backend requires PyDrive installationPlease read the manpage to fix.`

**Comment by wernight** [comment]
Looks like something missing indeed, even though there is a line `pip install pydrive==1.2.1 `. May be outdated.

**Comment by ghost** [comment]
Stumbled upon the same problem.

Using `pip install pydrive` works, so outdated version...

**Comment by wernight** [comment]
http://duplicity.nongnu.org/duplicity.1.html#sect30 seems that this is done. I've upgraded to 1.3.1, may be check http://duplicity.nongnu.org/duplicity.1.html#sect22 to see if it works after pulling the latest version (should be updating within 10 min).
