### ISSUE TITLE
Stable and latest point to the same docker hash without paramiko

### ISSUE THREAD

**Issue by Muscaw** [wernight/docker-duplicity#26]
@wernight I am using the docker-duplicity image with paramiko for remote backup. Since the last commits, the image does not contain paramiko anymore and duplicity fails.

According to https://hub.docker.com/r/wernight/duplicity/tags, the digest for stable and latest are the same and point to the docker image available in the stable folder (without paramiko).

See picture 
![image](https://github.com/wernight/docker-duplicity/assets/1104294/ee022dd0-7077-4841-99b0-8cf86400ceed)

For now, it seems the images are pushed manually . I can provide some automation using Github actions for updating the images if you are interested

**Comment by wernight** [comment]
Yes good idea. Haven't used those yet so if you can it'd be great. I may not reply immediately however I'll approve and merge if I see it. I did manual pushes but it's not something I like because it's less reliable (trustworthy) compared to an auto-push from CI).

**Comment by Muscaw** [comment]
@wernight You can find a PR that provides a simple automation to push images to docker hub. It triggers on tag creation (following the semver format major.minor.patch).

Let me know if that works out for you #27

**Comment by Muscaw** [comment]
The PR is now merged. I'll close this issue. Thanks for providing the image @wernight
