### ISSUE TITLE
Error on .cache dir

### ISSUE THREAD

**Issue by muka** [wernight/docker-duplicity#6]
Hello,
thanks for this useful image. I followed the readme for google drive but I am stuck on this error.

```
Specified archive directory '/home/duplicity/.cache/duplicity/9dab3bb458bb65e6ad73d147c338aec2' does not exist, or is not a directory
```

Seems like duplicity cannot use the mounted `.cache` directory properly, have you ever experienced such error?

Thank you
Regards

**Comment by wernight** [comment]
Not really. I'd check the access rights on that directory and possibly re-create the .cache.

**Comment by muka** [comment]
Thank you,
seems not the case, but will check better. Closing in the meantime

**Comment by AshishDadhich4h2** [comment]
Hi,
I am facing same above issue.
![image](https://user-images.githubusercontent.com/37674243/62547869-8ec6ab80-b82b-11e9-902f-ca360a3a7ae1.png)

even I tried to run multiplie times .

**Comment by dafriedmann** [comment]
> Hi,
> I am facing same above issue.
> ![image](https://user-images.githubusercontent.com/37674243/62547869-8ec6ab80-b82b-11e9-902f-ca360a3a7ae1.png)
> 
> even I tried to run multiplie times .

Hi there, 
I got the same issue. Checking the permissions showed: .cache/ and .gnupg/ where set to root:root.
Temp. fix would be to set the permissions manually on the host eg.: `sudo chown dockeruser:dockeruser .cache/`.
I assume this only shows up when using a different docker user than root.
